# Generated by Django 4.2.4 on 2023-08-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_cancel_permission', 'Can cancel product publication'), ('can_change_desc_permission', 'Can change product description'), ('can_change_category_permission', 'Can change product category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
