# Generated by Django 4.2.3 on 2023-07-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
