# Generated by Django 4.2.4 on 2023-08-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'not active')], verbose_name='признак активности'),
        ),
    ]
